export enum Commands {
    Start = "!startrpg",
    Join = "!join",
    Leave = "!leave",
    Attack = "!attack",
    Defend = "!defend",
    Heal = "!heal",
    Stats = "!stats",
    Players = "!players",
    Help = "!help",
    AttackEmote = "[emote:4029575:elderwiggleaksiyonSaldir]",
    DefendEmote = "![emote:4029578:elderwiggleaksiyonSavun]",
    HealEmote = "[emote:4029577:elderwiggleaksiyonCanver]",
    ArcherEmote = "[emote:4029549:elderwigglesinifOkcu]",
    DefenderEmote = "[emote:4029553:elderwigglesinifSavunmaci]",
    HealerEmote = "[emote:4029551:elderwigglesinifSifaci]",
}